name: Validate GitHub Actions

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/actions/**/action.yml
  push:
    branches:
      - master
    paths:
      - .github/actions/**/action.yml

permissions:
  contents: read

jobs:
  yaml-syntax:
    name: Validate action YAML syntax
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Validate YAML syntax
        uses: GrantBirki/json-yaml-validate@v5
        with:
          files: .github/actions/**/action.yml

  action-metadata-schema:
    name: Validate action metadata schema
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Validate action.yml metadata
        uses: dsanders11/json-schema-validate-action@f04ef3bca791388d2bd9ff3a50b27d1b2572158e # v2.1.0
        with:
          files: .github/actions/**/action.yml
          schema: https://raw.githubusercontent.com/SchemaStore/schemastore/d9d98e69894ebd7a50965dc58d61951e9d7f23a7/src/schemas/json/github-action.json
